#!/bin/bash -exu
#
# Script to start/stop shapi daemon
#
# USAGE
#
# $ shapid start|stop
#

debug=0

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
export script_dir

export SHAPI_HOME=$(readlink -f "${SHAPI_HOME:-$script_dir/..}" )
if [[ "$SHAPI_HOME" = "" ]]
then
	echo "SHAPI_HOME unreadable!"
	exit 1
fi

mkdir -p "$SHAPI_HOME"/logs

# Generate the config file
envsubst '$SHAPI_HOME' < "$SHAPI_HOME"/src/shapid_config.template > "$SHAPI_HOME"/daemon/shapid_config

if [[ "${1}" == "start" ]]
then
    # generate the host key if it doesn't exist
    if [[ ! -e "${SHAPI_HOME}"/daemon/shapid_host_rsa_key ]]
    then
        ssh-keygen -f "${SHAPI_HOME}"/daemon/shapid_host_rsa_key -N '' -t rsa
    fi

    # copy the binary for sshd if it's newer
    if [[ /usr/sbin/sshd -nt "$SHAPI_HOME"/bin/shapid ]]
    then
        cp -p /usr/sbin/sshd "$SHAPI_HOME"/bin/shapid
    fi

    if [ "$debug" != "0" ]
    then
        nohup "$SHAPI_HOME"/bin/shapid -E "$SHAPI_HOME"/logs/shapid.log -f "$SHAPI_HOME"/daemon/shapid_config >> logs/nohup.log &
    else
        nohup "$SHAPI_HOME"/bin/shapid -f "$SHAPI_HOME"/daemon/shapid_config >> logs/nohup.log &
    fi
    exit 0
fi

if [ -e "$SHAPI_HOME"/daemon/shapid.pid ]
then
	kill $(cat "$SHAPI_HOME"/daemon/shapid.pid ) || true
fi



